sudo: true

language: python

matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: required
          python: "3.4"
          dist: trusty

        - os: linux
          sudo: required
          python: "3.5"
          dist: trusty

        - os: linux
          sudo: required
          python: "3.6"
          dist: trusty

        # Use generic language for osx
        - os: osx
          language: generic
          python: "3.4"
          before_install:
            - brew upgrade https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb
            - bew install python@2

        # - os: osx
        #   language: generic
        #   python: "3.5"
        #
        # - os: osx
        #   language: generic
        #   python: "3.6"

env:
  -  TRAVISBUILD="True"

install:

  - python3 setup.py install

script:
    - circtools --help
