sudo: true

language: python

os:
  - linux
  - osx

env:
  -  TRAVISBUILD="True"

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install bedtools

install:

  - python setup.py install

script:
    - circtools --help
