sudo:                      true

language:                  python

matrix:
    include:
        # Use the built in venv for linux builds
         - os:             linux
           sudo:           required
           python:         "3.4"
           dist:           trusty
           before_install:
             - sudo apt-get install libssl1.0.0
             - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
             - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
             - gpg -a --export E084DAB9 | sudo apt-key add -
             - sudo apt-get update -qq
             - sudo apt-get -y --no-install-recommends install r-base build-essential gcc g++ gfortran libblas-dev liblapack-dev libncurses5-dev libreadline-dev libjpeg-dev libpcre3-dev libpng-dev zlib1g-dev libbz2-dev liblzma-dev libgit2-dev libssh2-1-dev

         - os:             linux
           sudo:           required
           python:         "3.5"
           dist:           trusty
           before_install:
             - sudo apt-get install libssl1.0.0
             - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
             - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
             - gpg -a --export E084DAB9 | sudo apt-key add -
             - sudo apt-get update -qq
             - sudo apt-get -y --no-install-recommends install r-base build-essential gcc g++ gfortran libblas-dev liblapack-dev libncurses5-dev libreadline-dev libjpeg-dev libpcre3-dev libpng-dev zlib1g-dev libbz2-dev liblzma-dev libgit2-dev libssh2-1-dev

         - os:             linux
           sudo:           required
           python:         "3.6"
           dist:           trusty
           before_install:
             - sudo apt-get install libssl1.0.0
             - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
             - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
             - gpg -a --export E084DAB9 | sudo apt-key add -
             - sudo apt-get update -qq
             - sudo apt-get -y --no-install-recommends install r-base build-essential gcc g++ gfortran libblas-dev liblapack-dev libncurses5-dev libreadline-dev libjpeg-dev libpcre3-dev libpng-dev zlib1g-dev libbz2-dev liblzma-dev libgit2-dev libssh2-1-dev

         - os:             osx
           language:       generic
           python:         "3.6"
           before_install:
           # below the formula for python 3.6
             - brew upgrade https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb
             - brew install python@2
             - brew cask uninstall oclint
             - brew install R
             - brew install md5sha1sum


env:
  - TRAVISBUILD="True"

install:
  - python3 setup.py install

script:
    - circtools --version
    - ./tests/01_test_dcc.sh
    - ./tests/02_test_quickcheck.sh