sudo: true

language: python

os:
  - linux

env:
  -  TRAVISBUILD="True"

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install bedtools
  - sudo apt-get install r-base

install:

  - python setup.py install

script:
    - circtools --help
